Minor formatting updates
SingleError: adding `omitempty` to `Details` and `WrappedValue` so that these properties aren't displayed when they don't need to be.